
version: '3.5'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: gancio
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data

  app:
    env_file: .env.production
    build: .
    ports:
      - '12300:12300'
    volumes:
      - ./uploads:/usr/src/app/uploads

    links:
      - db

