version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      # - ./db.sql:docker-entrypoint-initdb.d/db.sql
      - db:/var/lib/postgres
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=gancio
      - POSTGRES_DB=gancio
      - POSTGRES_PASSWORD=gancio
    restart: always
    ports:
        - 5432:5432
  app:
    image: node:latest
    container_name: gancio
    build: .
    volumes:
      - ./db.sqlite:/data/gancio/db.sqlite
      - ./gancio_config.json:/data/gancio/gancio_config.json:ro
      - ./uploads:/data/gancio/uploads
    depends_on: 
        - db
    ports:
        - 13120:13120
volumes:
    db:
    gancio:


