version: '3'

services:
  gancio:
    build: .
    restart: always
    image: node:buster
    user: node
    container_name: gancio
    environment:
      - PATH=$PATH:/home/node/.yarn/bin
      - GANCIO_DATA=/home/node/data
    command: gancio start --docker
    volumes:
      - ./data:/home/node/data
    ports:
      - "127.0.0.1:13120:13120"
