version: '3'

services:
  db:
    image: mariadb
    container_name: mariadb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=gancio
      - MARIADB_DATABASE=gancio
      - MARIADB_PASSWORD=gancio
    restart: always
  gancio:
    build: .
    restart: always
    image: node:buster
    container_name: gancio
    environment:
      - PATH=$PATH:/home/node/.yarn/bin
      - GANCIO_DATA=/home/node/data
      - NODE_ENV=production
    command: gancio start --docker
    entrypoint: /entrypoint.sh
    volumes:
      - ./data:/home/node/data
    ports:
      - "127.0.0.1:13120:13120"
    depends_on:
        - db
